version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword  # Set a non-empty password here
      POSTGRES_DB: Moneta_Media
    ports:
    - "5434:5432"  # Map external port 5434 to internal port 5432
    networks:
      - monetamedia-network

  app:
    build: .
    ports:
      - "9090:9090"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/Moneta_Media  # Use the internal port 5432 and the service name `postgres`
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: yourpassword  # Ensure this matches the password set for the postgres service
    networks:
      - monetamedia-network

networks:
  monetamedia-network:
    driver: bridge

